### ISSUE TITLE
4axis setting

### ISSUE THREAD

**Issue by xroperx** [kcjengr/probe_basic#12]
The screen doesnt start with 4axis setting on start up, the setting is stored like it should but you have to change to 3 axis then 4axis again to get the screen in 4axis mode.

**Comment by Lcvette** [comment]
yes this is a known issue that needs to be resolved still.. will post an update when it has been resolved

**Comment by Lcvette** [comment]
we have set it up to only use the ini for the axis setup going forward for simplicities sake:


[TRAJ]
AXES = 4
COORDINATES = X Y Z A
