### ISSUE TITLE
Deslecting Insall pyqtvcp 3.6 still installs it

### ISSUE THREAD

**Issue by joco-nz** [kcjengr/probe_basic#15]
There is an option to deselect install of 3.6 but when I deselected the option so that 3.7 would still be used the installer went ahead and installed 3.6 anyway.

**Comment by TurBoss** [comment]
Hello,

The new installer fixes this issues
http://repository.qtpyvcp.com/repo/pb/bin/ProbeBasic-Installer-0.2.9rc5.run

sorry for the late reply

**Comment by TurBoss** [comment]
fixed on v0.2.9
