### ISSUE TITLE
Override limits Issue

### ISSUE THREAD

**Issue by chaertl1** [kcjengr/probe_basic#16]
I'm not able to use the jog buttons for an axis that has triped a limit switch.
Using the override limits from the machine menu does not work.

Procedure:
- Use the default example configuration 
- Set a limit switch using hal show
- you will get the message that a limit switch was tripped
- Select Overrirde Limits from the machine menu
- Try to jog

**Comment by KurtJacobson** [comment]
@chaertl1 Can you please confirm that this issue has been fixed with the merge of kcjengr/qtpyvcp#44?
