### ISSUE TITLE
Development Install Description is not up to date?

### ISSUE THREAD

**Issue by Gnevko** [kcjengr/probe_basic#22]
Hi,
the following command in the Development Install (https://kcjengr.github.io/probe_basic/dev_install.html):

 `cp -r ~/probe_basic/config/xyzab/ ~/linuxcnc/configs/`

cann't be executed:

`cp: cannot stat '/home/cnc/probe_basic/config/xyzab/': No such file or directory`

**Comment by TurBoss** [comment]
thanks, please check the up to date docs 
https://www.qtpyvcp.com/install/dev_install.html

**Comment by Gnevko** [comment]
sorry for my English, but we speaking about ProbeBasic "Development Install", not about  QtPyVCP ...

**Comment by TurBoss** [comment]
oh very true

**Comment by TurBoss** [comment]
https://kcjengr.github.io/probe_basic/dev_install.html

qcompile and config path where fixed

it should take some minutes to show up
thanks!

**Comment by Gnevko** [comment]
1) config path where fixed - ok
2) qcompile is still missing for **Probe Basic** part - not ok

**Comment by TurBoss** [comment]
now its fixed

thanks !

**Comment by Gnevko** [comment]
It seams to be ok now, thank you!

**Comment by TurBoss** [comment]
now its fixed

thanks !
