### ISSUE TITLE
Probe Basic Installer

### ISSUE THREAD

**Issue by Gnevko** [kcjengr/probe_basic#25]
The functions "Add or remove components" and "Update components" are not working properly:

![screen](https://user-images.githubusercontent.com/35346815/97890538-f0770d80-1d2d-11eb-9fb1-9c5f95cd80a2.png)

**Comment by TurBoss** [comment]
thats the current stable installer it oly allows to install or uninstall

https://github.com/kcjengr/probe_basic/releases/tag/v0.2.9rc5 <- this is a release candidate it should work fine

**Comment by TurBoss** [comment]
fixed on v0.2.9
