### ISSUE TITLE
Probe Basic Lathe: Display resolution 

### ISSUE THREAD

**Issue by Gnevko** [kcjengr/probe_basic#26]
Ok, let's start😀

It seams that lathe version doesn't fit the 1920x1080 display resolution. It's a bit bigger as it should be. 

![IMG_20201103_092524.jpg](https://user-images.githubusercontent.com/35346815/97963225-0381f000-1db7-11eb-9f5c-db835e37abe2.jpg)
![IMG_20201103_092515.jpg](https://user-images.githubusercontent.com/35346815/97963239-08df3a80-1db7-11eb-99e4-c2aeea2decc5.jpg)

**Comment by Lcvette** [comment]
This has been fixed in Master and will come out in the next release!
