### ISSUE TITLE
Probe Basic Lathe: delete tool and save table

### ISSUE THREAD

**Issue by Gnevko** [kcjengr/probe_basic#29]
1) Set tool 1 as current tool ( on the main or touch off screen)
2) delete tool 1 from the tool table (on the tool table screen)
3) Press "Save table" button

Traceback (most recent call last):
  File "/home/cnc/qtpyvcp/qtpyvcp/plugins/tool_table.py", line 250, in reloadToolTable
    tool_table = self.loadToolTable()
  File "/home/cnc/qtpyvcp/qtpyvcp/plugins/tool_table.py", line 324, in loadToolTable
    self.current_tool.setValue(self.TOOL_TABLE[STATUS.tool_in_spindle.getValue()])
KeyError: 1

**Comment by Lcvette** [comment]
I am able to reproduce error and will look at it!

**Comment by KurtJacobson** [comment]
A warning dialog will now be shown when trying to delete a tool that is currently in the spindle.

![2021-01-31_13-09](https://user-images.githubusercontent.com/19997275/106393674-83275700-63c6-11eb-8580-8bd17cc21305.png)

**Comment by KurtJacobson** [comment]
I guess the message should read different for a lathe ...
