### ISSUE TITLE
Probe Basic Lathe: Menu Mashine -> Set Works Offsets

### ISSUE THREAD

**Issue by Gnevko** [kcjengr/probe_basic#31]
Traceback (most recent call last):
  File "/home/cnc/qtpyvcp/qtpyvcp/widgets/form_widgets/main_window.py", line 174, in <lambda>
    menu_action.triggered.connect(lambda checked: method(*args, **kwargs))
TypeError: showDialog() takes exactly 2 arguments (17 given)

**Comment by Lcvette** [comment]
need more information on how to reproduce please!

**Comment by Lcvette** [comment]
please provide more information on this issue so we can recreate, you can reopen another issue with the new information!
