### ISSUE TITLE
Probe Basic Lathe: Display of real Spindle Speed

### ISSUE THREAD

**Issue by Gnevko** [kcjengr/probe_basic#35]
Hi, it seams not much loss is here in the last time :) 

The display of real spindle speed doesn't work correctly:

![screen01](https://user-images.githubusercontent.com/35346815/98449593-08d39780-2135-11eb-8945-b43c847ac0ba.png)

More details: https://forum.linuxcnc.org/27-driver-boards/37894-mesa-7i95?start=120#188605

**Comment by Lcvette** [comment]
that is not the display of real spindle speed, that is the currently commanded spindle speed ie the last S word entered so the user knows what M3/M4 will do, you could change this to show actual spindle speed in the dev version if you wanted pretty easily though!

**Comment by flounderscore** [comment]
+1 please add this option for mill, too.
