### ISSUE TITLE
Probe Basic Lathe: orientation of tool path

### ISSUE THREAD

**Issue by Gnevko** [kcjengr/probe_basic#36]
With the same configuration in Axis:

![screen02](https://user-images.githubusercontent.com/35346815/98565215-a0f48c80-22ad-11eb-8c78-26c73763f705.png)

Probe Basic Lathe:

![screen03](https://user-images.githubusercontent.com/35346815/98565272-b2d62f80-22ad-11eb-86da-9e372fc926cc.png)

**Comment by TurBoss** [comment]
the view is inverted I'll take a look

**Comment by TurBoss** [comment]
it has to do with the default view

can you try to change view from the "View" menu then "View Angle"and "XZ Lathe" or "XZ2
Lathe"

Thanks

**Comment by Gnevko** [comment]
Thank you! 
1) It works, but I would suggest to use BACK_TOOL_LATHE = 1 parameter from INI File, to manage the view orientation. 

2) "View" menu as a lot of other items, but I'm not sure if all of them make sense  for  the Lathe
![image](https://user-images.githubusercontent.com/35346815/99143331-d5c16480-265c-11eb-93c0-244e44ccd47e.png)

3) The view displays only machine coordinate system
![image](https://user-images.githubusercontent.com/35346815/99143369-18833c80-265d-11eb-9abb-f9bb534364f9.png)

I didn't  found any possibility to change it for work coordinates. It seams, that the following menu Items don't work correctly
![image](https://user-images.githubusercontent.com/35346815/99143414-6c8e2100-265d-11eb-966c-18871b7a89c5.png)

**Comment by TurBoss** [comment]
makes sense to hide non lathe options when lathe is setup and the opposite

machine and part bounds require a bit of work :|
