### ISSUE TITLE
Critical Error: Tool N can't be found

### ISSUE THREAD

**Issue by Gnevko** [kcjengr/probe_basic#37]
LinuxCnc 2.9
ProbeBasic - development

Any changes in the tool table leads to the following error: linuxcnc cann't "see" all tools anymore. If I try to use for example "T1 M6"  command then I receive the error message: "Tool 1 can't be found". After that it helps only restore tool file from my backup.

**Comment by TurBoss** [comment]
Just tested on 2.80 and save seems to work
🤔

**Comment by TurBoss** [comment]
Hello,

currently probe_basic develop install install latest qtpyvcp but not git branch "master"
could you please if not already install qypyvcp in develop mode 

it should be already fixed

Thank you!

**Comment by Gnevko** [comment]
Hi, I had already development version installed. Today I reinstall it again and it looks fine now.
Thank you.
(PS: about PB Lathe - is the live here?)

**Comment by TurBoss** [comment]
Hello,

Thanks

about lathe I'll try to address the issues

**Comment by Gnevko** [comment]
Hm ...  now I have the same issue with Probe Basic Lathe. Any changes lead to corrupted tool table file :(

**Comment by Lcvette** [comment]
fixed
