### ISSUE TITLE
Probe Basic Lathe: Touch Off Routine for X Axis

### ISSUE THREAD

**Issue by Gnevko** [kcjengr/probe_basic#39]
Step 1) load the muster tool (in my case it is the tool number 1)
Step 2) take a test cut with the muster tool  
Step 3) write the measured diameter into X DIA field, let it be 40mm

![image](https://user-images.githubusercontent.com/35346815/99144065-02787a80-2663-11eb-89d5-65f68444b198.png)

Step 4) load the tool number 2 and make a test cut again.
Step 5) write the new measured diameter into TOUCH X Field. Let it be 30mm (it means, that tool number 2 is 5mm longer as the muster tool. )

![image](https://user-images.githubusercontent.com/35346815/99144277-dbbb4380-2664-11eb-8f34-516fab969630.png)

and press TOUCH X button.

**Expectation:** in the tool table the tool number 2 should have X Offset = 5

**Reallity:**
![image](https://user-images.githubusercontent.com/35346815/99144362-74ea5a00-2665-11eb-9067-fc9649a73aed.png)

**Comment by Lcvette** [comment]
what you are describing is master tool mode, you should be in master tool mode for it to function as you are describing the expectation. standard mode is for repeatable cnc turret machines that define all tools from the spindle zero point and are correct after precision homing sequence completes.
