### ISSUE TITLE
Moving a text cursor in an input field

### ISSUE THREAD

**Issue by Gnevko** [kcjengr/probe_basic#4]
Hi,

1) go to the tool table tab
2) write something in the remark field 
<img width="789" alt="Снимок экрана 2019-11-29 в 14 29 46" src="https://user-images.githubusercontent.com/35346815/69872251-32ddd200-12b5-11ea-9eeb-f16da46f1968.png">
3) and then try to use "left" or "right" arrows to move the text cursor, for example back 
<img width="514" alt="Снимок экрана 2019-11-29 в 14 29 57" src="https://user-images.githubusercontent.com/35346815/69872329-6d476f00-12b5-11ea-8e61-8eccf8bf6d76.png">

**Comment by KurtJacobson** [comment]
This was cause by a bug in the jog logic in QtPyVCP. Fixed with kcjengr/qtpyvcp@88d80909cce9efcae0f7a1820a14da537f399cf6
