### ISSUE TITLE
Probe Basic Lathe: Critical Error: Tool N can't be found

### ISSUE THREAD

**Issue by Gnevko** [kcjengr/probe_basic#40]
It's a bit strange, but the loading of latest development version of qtpyvcp fix the problem within Probe Basic, but now I have the same issue within Probe Basic lathe!

What it interesting, with previous dev version of qtpyvcp the tool table in the Probe Basic lathe had work correctly.

**Comment by Lcvette** [comment]
can you elaborate on the issue im trying to reproduce in both release and dev version

**Comment by Lcvette** [comment]
I tried loading all tools and it is working correctly as far as i can see and loading a tool not defined in the tool table results in an error message. marking closed, please reopen with more information!  Thanks Gnevko!

**Comment by Lcvette** [comment]
think we found the problem and have corrected it will be fixed in next release
