### ISSUE TITLE
Configuring tool touch off

### ISSUE THREAD

**Issue by cerdo1** [kcjengr/probe_basic#41]
Hi.
I am trying to set the tool touch off using a manual tool change.

I would be interested in measuring the 3D probe, and from there, with each M6 tool change, make a probe of the height with its tool touch off in a position on the table. But I am not able to get it to work using the M6 command.
I have remapped to
REMAP = M6 modalgroup = 6 ngc = tool_touch_off
I don't know if it's correct, or what I should do more.
Could someone tell me what to do?

Thanks and best regards!

**Comment by Lcvette** [comment]
you will need to write a custom subroutine for that and add it to your M6 macros remap.  store the new subroutine in the subroutines folder in the config file and should work once all is connceted!
