### ISSUE TITLE
ToolTable gets Blank on Chars like Ä Ü Ö

### ISSUE THREAD

**Issue by Moshkopp** [kcjengr/probe_basic#43]
Hey there, 

got an an issue on save the toolTable, if I use  Ä Ö Ü in  comment field. 

`Traceback (most recent call last):
  File "/home/cnc/.local/lib/python2.7/site-packages/qtpyvcp/widgets/input_widgets/tool_table.py", line 252, in saveToolTable
    self.tool_model.saveToolTable()
  File "/home/cnc/.local/lib/python2.7/site-packages/qtpyvcp/widgets/input_widgets/tool_table.py", line 200, in saveToolTable
    self.tt.saveToolTable(self._tool_table, self._columns)
  File "/home/cnc/.local/lib/python2.7/site-packages/qtpyvcp/plugins/tool_table.py", line 422, in saveToolTable
    fh.write('\n'.join(lines))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 97: ordinal not in range(128)`

after that Msg, my ToolTable.tbl gets complete empty.

**Comment by TurBoss** [comment]
Hello,

this is a known issue that may be fixed

what version do you use?

thanks

find latest version in the release section

**Comment by Moshkopp** [comment]
Hello,

I installed the latest stable, an also the develop from Masterbranch. 

`cnc@cnc:~$ probe_basic -v
QtPyVCP 0.3.13+1.g2a45555e.3.gd45a9315, Probe Basic vv0.3.4+5.g4623efa.dirty
cnc@cnc:~$ ^C
`

**Comment by TurBoss** [comment]
thank you so much I thin I managed to fix 

if you could test latest qtpyvcp from git?

**Comment by TurBoss** [comment]
> this is a known issue that may be fixed

thatwas other issue actually

**Comment by Moshkopp** [comment]
Runs like a charme, you fixed it. Thank you.

**Comment by TurBoss** [comment]
Thank you too!
