### ISSUE TITLE
Allow custom distance for angle probing

### ISSUE THREAD

**Issue by sttts** [kcjengr/probe_basic#45]
When probing the angle of an object, the distance between the two measurement points is very small (1mm or 2?), leading to inprecise results. With rectangular object I would want to have the measurements 10 or 20mm apart.

**Comment by sttts** [comment]
After reading the code of the subroutine, this is `edge_width`, isn't it? So there is rather a lack of docs for that feature.

**Comment by Moshkopp** [comment]
Yes, it is in fact the distance between the 2 measuring points.
