### ISSUE TITLE
Edge Angle offsets 

### ISSUE THREAD

**Issue by Moshkopp** [kcjengr/probe_basic#47]
Got a Problem with the Edge Angle, 
After I measure the Edge Angle of my Object I run the First gCode. 
After finishing 1. Side I turn my Object and load the 2. gcode. Measure Edge Angle again and it seems that he always had the Offsets from first Measuring. 
I cleared Offsets measure again and it fits. But in Toolpath visulization it looks strange. 

![Screenshot 2021-04-04 222005](https://user-images.githubusercontent.com/24791143/113556381-ae176c80-95fc-11eb-93f1-c96e942532fa.png)

but he Runs the right way...

**Comment by Lcvette** [comment]
you need to clear the backplotter maybe? also in the offsets page the rotation offset can be seen if one is active it is under R on the far right, when you clear the offsets table you must also reload and save the table for the offsets to be zeroed if done that way.
