### ISSUE TITLE
Jogging after change jogging type

### ISSUE THREAD

**Issue by Gnevko** [kcjengr/probe_basic#5]
1) Start LinuxCNC
2) Press "e-stop" and "power"
3) try to jog x axis - works perfect
4) change jogging type (left mouse button)  from "JOG" to "1.00"
5) try to jog x axis again in both directions - fail! because now the arrows (left, right) move the focus between job buttons!

**Comment by KurtJacobson** [comment]
Hello @Gnevko, this was actually caused by the QtPyVCP JogIncrements widget stealing the input focus. I have fixed this with kcjengr/qtpyvcp@9bb4849a675bb4222bc612106cb6e5e6948f8b10

Thanks for the bug report!
