### ISSUE TITLE
Probe Basic Vertical

### ISSUE THREAD

**Issue by OpenSourceDevelop** [kcjengr/probe_basic#50]
Hello

Have Linuxcnc 2.8.1 with Probe Basic v0.3.4 running and working. So far so good :)

But i want to try Probe Basic Vertical... but there is no sample config..

i have done the compiling:

qcompile home/cnc/probe_basic/probe_basic_vertical

what now?

**Comment by Lcvette** [comment]
probe basic vertical is lagging behind and is not ready for use, once regular probe basic and probe basic lathe are wrapped up we will return focus to the vertical screen so it will be completely updated
