### ISSUE TITLE
Install problems

### ISSUE THREAD

**Issue by dlhenke** [kcjengr/probe_basic#52]
I can not install probe_basic.. 
--2021-06-08 10:15:41--  (try:20)  https://repository.qtpyvcp.com/repo/pb/repo/com.probebasic.core/0.4.0dist.7z
Connecting to repository.qtpyvcp.com (repository.qtpyvcp.com)|54.37.56.77|:443... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 11605350 (11M), 9743146 (9.3M) remaining [application/x-7z-compressed]
Saving to: ‘0.4.0dist.7z’

0.4.0dist.7z                   16%[+++++++>                                        ]   1.87M   195KB/s    in 0.5s    

2021-06-08 10:15:42 (195 KB/s) - Read error at byte 1960213/11605350 (Error decoding the received TLS packet.). Giving up.

**Comment by TurBoss** [comment]
hello, 
thanks for the report, the server ran out of space.

fixed

Thanks you
