### ISSUE TITLE
Spindle load indicator text "{P}%"

### ISSUE THREAD

**Issue by flounderscore** [kcjengr/probe_basic#57]
I just upgraded my system to latest LinuxCNC, qtpyvcp, and probe_basic (all python3). The spindle load indicator text is shown as "{P}%", however the bargraph in the background appears to be working correctly.

**Comment by TurBoss** [comment]
hello, thanks for the report!

I found the issue and managed to fix

if you could tests the git branches I just created for qtpyvcp and probe_basic?
they are both called spindle_load_template

```
git checkout spindle_load_template
```




thank you

**Comment by TurBoss** [comment]
fix went master

**Comment by flounderscore** [comment]
Thanks! Sorry, I did not have time to test it.
