### ISSUE TITLE
Rack Tool Change UI

### ISSUE THREAD

**Issue by flowers84** [kcjengr/probe_basic#59]
Will there be a change in the UI to a Rack tool change in the near future

**Comment by Lcvette** [comment]
there has been some work done on this, but it may be some time before it is implemented. probably after all of the installation changes are finished with Linuxcnc 2.9+ is done and a new installer method to work with probe basic.

**Comment by flowers84** [comment]
Thanks a lot, 
i am waiting every day ;D

**Comment by tataetae** [comment]
Any update on this? I am building a rack tool changer and this got me interested :D

**Comment by Lcvette** [comment]
> Any update on this? I am building a rack tool changer and this got me interested :D

It's up and live on develop apt install version!
