### ISSUE TITLE
Probe_basic will not load 

### ISSUE THREAD

**Issue by T-Workshop** [kcjengr/probe_basic#61]
Hi,
I am not sure if it's a problem to be posting here but I'll try.
I did an installation of LinuxCNC 2.8.2 and Probe_basic according to your website.
Sadly, every time I try to open LinuxCNC with probe basic the GUI only briefly flashes and then reports an error (attached). 
I am not a linux guy so I have no idea what to do.
My system is currently set to Czech so I hope there's not unreadable info in the report file .

Thanks for any help.

Tomas

[linuxcnc_info.txt](https://github.com/kcjengr/probe_basic/files/8667906/linuxcnc_info.txt)

**Comment by Lcvette** [comment]
not sure if you resolved this, but the file you sent did not have the debug report on it to see what caused the error. but those in most cases are typically configuration issues that need to be resolved.
