### ISSUE TITLE
Installer Error

### ISSUE THREAD

**Issue by akritiadmin** [kcjengr/probe_basic#62]
Error during installation process (com.probebasic.core):
Execution failed (Unexpected exit code: 1): "python -m pip install --user --upgrade git+https://github.com/kcjengr/qtpyvcp.git@python2_maintenance"

**_Complete list of details from the Installer -_**

Preparing the installation...

Downloading packages...
Downloading archive "0.1.0-1content.7z.sha1" for component Fonts.
Downloading archive "0.1.0-1content.7z" for component Fonts.
Downloading archive "py2+3.g231c7ffdist.7z.sha1" for component Probe Basic.
Downloading archive "py2+3.g231c7ffdist.7z" for component Probe Basic.
Downloading archive "py2+3.g231c7fficons.7z.sha1" for component Probe Basic.
Downloading archive "py2+3.g231c7fficons.7z" for component Probe Basic.
Downloading archive "0.1.0-1pb_examples.7z.sha1" for component Gcode examples.
Downloading archive "0.1.0-1pb_examples.7z" for component Gcode examples.
Downloading archive "0.1.0-1config.7z.sha1" for component Config examples.
Downloading archive "0.1.0-1config.7z" for component Config examples.

Installing component Fonts
Extracting "0.1.0-1content.7z"
Extracting "0.1.0-1content.7z"
Done

Installing component Probe Basic
Extracting "py2+3.g231c7ffdist.7z"
Extracting "py2+3.g231c7ffdist.7z"
Extracting "py2+3.g231c7fficons.7z"
Extracting "py2+3.g231c7fficons.7z"
Requirement already up-to-date: pip in /home/akriti/.local/lib/python2.7/site-packages (20.3.4)

Requirement already up-to-date: wheel in /home/akriti/.local/lib/python2.7/site-packages (0.37.1)

Collecting git+https://github.com/kcjengr/qtpyvcp.git@python2_maintenance

  Cloning https://github.com/kcjengr/qtpyvcp.git (to revision python2_maintenance) to /tmp/pip-req-build-iZEcBs

**Comment by Lcvette** [comment]
did you get this resolved?  I ran the installation here and it went without error, if you still need assistance, please let me know!

**Comment by akritiadmin** [comment]
Yes, it was resolved. We were using a monitor with the incorrect resolution. On a 1920x1080 resolution it worked perfectly.
