### ISSUE TITLE
can't download install script from quick start page

### ISSUE THREAD

**Issue by piflixe** [kcjengr/probe_basic#67]
in the [quick start guide](https://kcjengr.github.io/probe_basic/quick_start.html) the download of an [installer](https://repository.qtpyvcp.com/repo/pb-py2/bin/ProbeBasic-Installer-py2+3.g231c7ff.run) is recommended. 

The link seems not to work. Or am I just doing something very wrong? Tried klicking on the link and also using wget from the command line so far.

in the github releases I found a [0.4.0 installer](https://github.com/kcjengr/probe_basic/releases/download/0.4.0/ProbeBasic-Installer-0.4.0+18.g7a0e645.run). So maybe the link in the documentation can be changed to that or just point the the releases page?

**Comment by Andreg3127** [comment]
I am also having the same issue. I cannot download the installer script through my CNC computer or through my windows PC. Link appears to be dead.

**Comment by TurBoss** [comment]
hello, the server hosting that is offline

will be up as soon as possible

I'll report here

Thanks

**Comment by TurBoss** [comment]
and fixed
we are online again!
