### ISSUE TITLE
Calling Probe Routines from physical Switch

### ISSUE THREAD

**Issue by Alexfehr1987** [kcjengr/probe_basic#68]
When calling the subroutines for Probing via Hal the Parameters Set in PB are not found.
I made a physical Button matrix for probing on my cnc and want to call the probing routines with mdi command. All set parameters( eg. Probing feedrate) from PB are not found if I call the subroutine. I could edit all subroutines to hardcore these parameters, but then I would have to change all subroutines if I change something in PB.
Is there an easy way to transmit the nessesary parameters?
![image](https://user-images.githubusercontent.com/118825491/212447011-823c358e-fcf1-4546-83a0-e7c16307c255.png)

**Comment by Lcvette** [comment]
the probe routines in probe basic work by calling those parameters in using the coding in the subcall button widget python code.  normal subroutines can only call linuxcnc parameters such as numbered parameters from the var file or named parameters that are coded into its interpereter in linuxcnc.  you would probably need to either hard code like you said or perhaps connect the physical button to the interface subcall button. next time at dev i will see if i can see if that is possible, perhaps using a hal pin or a hidden set of hallpushbuttons connected to the probe subcall buttons would work.  kind of hacky, but it may be a stopgap solution until more development on the widget rules is completed to allow hal connections.
