### ISSUE TITLE
confusing information on compatibility

### ISSUE THREAD

**Issue by tcurdt** [kcjengr/probe_basic#75]
Maybe the README needs an update? What is it? Debian 11 or Debian 9?

<img width="805" alt="Screenshot 2023-07-21 at 01 58 58" src="https://github.com/kcjengr/probe_basic/assets/13697/39f5d77d-f43e-46f0-92ee-576a939b0342">

**Comment by TurBoss** [comment]
Hello,

Thanks I just fixed it to represent current main branch
