### ISSUE TITLE
"SPINDLE SPEED DISPLAY RPM SOURCE" setting not remembered

### ISSUE THREAD

**Issue by dpslwk** [kcjengr/probe_basic#99]
On the setting page we have "Spindle speed display rpm source" section with two buttons in the `spindlerpmsourcebtnGroup` group

* "CALCULATED SPINDLE RPM" `spindle_calculated_rpm`
* "ENCODER SPINDLE RPM" `spindle_encodr_rpm`
<img width="463" alt="Screenshot 2023-11-26 at 19 57 10" src="https://github.com/kcjengr/probe_basic/assets/234460/bb95d0bd-3d75-4e20-9e2e-b0bce07db00a">

these change the page of `spindle_rpm_source_widget` via some python (left spindle rpm box)

<img width="330" alt="Screenshot 2023-11-26 at 19 57 36" src="https://github.com/kcjengr/probe_basic/assets/234460/ddc3dc0c-9f9a-4f8a-8cb5-aa7af0b65b26">

but although these are `VCPSettingsPushButton`'s they have no `settingName` set and we are not remembering this state in anyway, so at launch PB always goes back to encoder rpm and not everyone has an encore or it  hooked up in hal

**Comment by Lcvette** [comment]
spindle speed is now fixed, link angular jog is not yet completed, need to look into that a bit more to see how the best way to resolve the connection would be.

**Comment by Lcvette** [comment]
I am going to close this issue but let open one just for the link angular jog issue to tidy up the fix list.
